=== comunedibari/payflowpa/sorgenti/posizione_debitorie/gepos-sorgenti/ebmonitor/library/converter/converter/docs/CBIInfTrfReq/xsd/CBITrfBonLogMsg.00.01.01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 (http://www.altova.com) by Giacomo Paci (CONSORZIO CUSTOMER TO BUSINESS INTERACTION - CBI) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:CBI:xsd:CBITrfBonLogMsg.00.01.01" targetNamespace="urn:CBI:xsd:CBITrfBonLogMsg.00.01.01" elementFormDefault="qualified">
	<!-- Dichiarazione del messaggio logico informativo di trasferibilità bonifico -->
	<xs:element name="CBITrfBonLogMsg" type="CBITrfBonLogMsg.00.01.01">
		<xs:annotation>
			<xs:documentation>1.3.2.1.1.
Messaggio logico di trasferibilità bonifici. Al momento è l'unico disponibile               </xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:simpleType name="Max105Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="105"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="AdvStsLogMsgHdrType">
		<xs:sequence>
			<xs:element name="MsgId" type="Max35Text">
				<xs:annotation>
					<xs:documentation>Identificativo del messaggio logico, univoco a parità di giornata e mittente</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="CreDtTm">
				<xs:annotation>
					<xs:documentation>Data e ora di creazione del messaggio logico</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="MsgTpCd">
				<xs:annotation>
					<xs:documentation>Tipologia di messaggio logico, resa in forma codificata. Assume il valore fisso TRASF-BON-ADV-STS</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="TRASF-BON-ADV-STS"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StsRsnType">
		<xs:choice>
			<xs:element name="Cd" type="Max256Text">
				<xs:annotation>
					<xs:documentation>Motivo espresso in forma codificata</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="Prtry" type="Max35Text">
				<xs:annotation>
					<xs:documentation>Motivo espresso in forma proprietaria, sulla base di un accordo tra le parti</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="StsRsnInfType">
		<xs:sequence>
			<xs:element name="StsRsn" type="StsRsnType">
				<xs:annotation>
					<xs:documentation>Motivo per il quale è stato generato lo stato di avanzamento</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="AddtlStsRsnInf" type="Max105Text" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Informazioni aggiuntive sullo stato, rese in testo libero</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="LogMsgStsCd">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ACTC"/>
			<xs:enumeration value="RJCT"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Definizione del messaggio logico informativo di trasferibilità bonifico -->
	<xs:complexType name="CBITrfBonLogMsg.00.01.01">
		<xs:sequence>
			<!-- Il CBIHeader contiene informazioni tipiche del circuito CBI, come ad esempio i codici SIA,
                 CUC, la data di creazione, l'identificativo del msg -->
			<xs:element name="LogMsgHdr" type="LogMsgHdrType">
				<xs:annotation>
					<xs:documentation>1.3.2.1.1.1.
Rappresenta l'header del messaggio logico. </xs:documentation>
				</xs:annotation>
			</xs:element>
			<!-- Il seguente blocco contiene le informazioni core di servizio, eventualmente riprese dal tracciato interbancario.
			In analogia agli attuali tracciati, e a quelli interbancari, potrebbe essere strutturato riportando in XML la struttura  "a record" -->
			<xs:element name="LogMsgCoreInf" type="LogMsgCoreInfType">
				<xs:annotation>
					<xs:documentation>1.3.2.1.1.2.
Informazioni specifiche del servizio, provenienti dall'interbancario. Da valutarne la strutturazione</xs:documentation>
				</xs:annotation>
			</xs:element>
			<!-- Il seguente blocco facoltativo potrebbe contenere eventuali info aggiuntive, come il link a documenti correlati o i documenti stessi codificati in base64 -->
			<!-- Tale blocco corrisponde all'attuale record di coda, con eventuali informazioni di quadratura -->
		</xs:sequence>
	</xs:complexType>
	<!-- Esempio di strutturazione in record che riprende i tracciati dell'interbancario -->
	<xs:complexType name="LogMsgCoreInfType">
		<xs:sequence>
			<xs:element name="Disp" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>1.3.2.1.1.2.1.
Ogni messaggio logico contiene una o più disposizioni</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="NumDisp" type="xs:positiveInteger">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.2.1.1
Numero progressivo occorrenze dispositive </xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="DispCreDt" type="Fixed6Num">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.2.1.2
Data di creazione della disposizione, espressa nel formato GGMMAA</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="IBANBnNew" type="IBANIdentifier">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.2.1.3
Coordinate IBAN banca new. Nuove coordinate del beneficiario a seguito del trasferimento</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="IBANBnOld" type="IBANIdentifier">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.2.1.4
Coordinate IBAN banca old. Vecchie coordinate del beneficiario verso le quali l'ordinante ha istruito il pagamento</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="CRO" type="Max16Text">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.2.1.5
Codice Riferimento Operazione del bonifico originario</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="Ord" type="Max40Text">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.2.1.6
Cliente ordinante. Contiene l’informazione “Cliente Ordinante: Anagrafica” presente nel bonifico
da routing (IDC041 - BON). Nome e cognome ovvero ragione sociale del soggetto ordinante. </xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="Benef" type="Max40Text">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.2.1.6
Cliente beneficiario. Contiene l’informazione “Cliente Destinatario: Anagrafica” presente nel bonifico
da routing (IDC051 - BON). Nome e cognome ovvero ragione sociale del Soggetto Beneficiario. </xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="CodRif" type="Max15Text" minOccurs="0">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.2.1.6
Codice di riferimento ad uso della nuova banca  </xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="Descr" type="Max75Text" minOccurs="0">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.2.1.7
Descrizione</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="CBIAddtlInf" type="Max140Text" minOccurs="0" maxOccurs="5">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.2.1.8
Informazioni aggiuntive ad uso della banca passiva. Gli standard CBI non fissano le modalità  di utilizzo di tale campo che possono invece essere demandate ad accordi bilaterali banca-azienda </xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="Max35Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="35"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max40Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="40"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max140Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="140"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max75Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="75"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max16Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="16"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max16TextNoBlank">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="16"/>
			<xs:whiteSpace value="collapse"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max15Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="15"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max7Num">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{1,7}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Fixed6Num">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{6,6}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max256Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="256"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="LogMsgHdrType">
		<xs:sequence>
			<xs:element name="MsgId" type="Max35Text">
				<xs:annotation>
					<xs:documentation>1.3.2.1.1.1.1
Identificativo del messaggio logico, univoco a parità di data creazione del messaggio logico, mittente e tipologia di messaggio.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="CreDtTm" type="ISODateTime">
				<xs:annotation>
					<xs:documentation>1.3.2.1.1.1.2
Data e ora di creazione del messaggio logico. Ai fini dell'univicità dell'identificativo del messaggio logico va considerata solo la parte data.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="MsgTpCd">
				<xs:annotation>
					<xs:documentation>1.3.2.1.1.1.3
Tipologia di messaggio logico, resa in forma codificata. Assume il valore fisso "TRF-BON".</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="TRF-BON"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Sndr">
				<xs:annotation>
					<xs:documentation>1.3.2.1.1.1.4.
Mittente del messaggio logico. E' la banca passiva dell'azienda ordinante</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="CUC" type="CUCIdentifier">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.1.4.1
Deve coincidere con il CUC dalla banca passiva, presente nell'HE2E come mittente logico del messaggio fisico</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="ABICd" type="ABIIdentifier" minOccurs="0">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.1.4.2
Codice ABI della banca mittente. Deve essere associato al codice CUC (controllo anagrafico sul Directory)  indicato nel campo precedente. </xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Rcvr">
				<xs:annotation>
					<xs:documentation>1.3.2.1.1.1.5.
Destinatario del messaggio logico. E' l'azienda ordinante alla quale viene data l'informazione circa l'avvenuto trasferimento del conto corrente del beneficiario</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="CUC" type="CUCIdentifier">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.1.5.1
CUC dell'azienda ordinante. Deve essere associata (controllo sul Directory) alla banca proponente destinataria della richiesta di servizio.</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="SIACd" type="SIAIdentifier" minOccurs="0">
							<xs:annotation>
								<xs:documentation>1.3.2.1.1.1.5.2
Codice SIA dell'azienda destinataria. Deve corrispondere in anagrafica (Directory) al codice CUC indicato nel campo precedente </xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="NbOfDisp" type="xs:positiveInteger">
				<xs:annotation>
					<xs:documentation>1.3.2.1.1.1.6
Numero di disposizioni contenute nel messaggio logico. Deve coincidere con il  numero dei blocchi Disp contenuti nel blocco di informazioni core di servizio</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="SIAIdentifier">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z0-9]{5,5}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CUCIdentifier">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z0-9]{8,8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ABIIdentifier">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{5,5}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="IBANIdentifier">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="CoordAzType">
		<xs:sequence>
			<xs:element name="SIACd" type="SIAIdentifier">
				<xs:annotation>
					<xs:documentation>1.3.2.1.1.2.1.5.1                   Codice SIA azienda</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="TpCdInd">
				<xs:annotation>
					<xs:documentation>1.3.2.1.1.2.1.5.2                  Tipo codice individuale</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="1"/>
						<xs:enumeration value="2"/>
						<xs:enumeration value="3"/>
						<xs:enumeration value="4"/>
						<xs:enumeration value="5"/>
						<xs:enumeration value="6"/>
						<xs:enumeration value="9"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CdInd" type="Max16TextNoBlank">
				<xs:annotation>
					<xs:documentation>1.3.2.1.1.2.1.5.3
Codice individuale</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="ISODateTime">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
</xs:schema>

=== comunedibari/payflowpa/sorgenti/posizione_debitorie/gepos-sorgenti/ebmonitor/library/converter/converter/docs/CBIInfTrfReq/xml/CBITrfBonLogMsg-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 sp1 (http://www.altova.com)-->
<CBITrfBonLogMsg xmlns="urn:CBI:xsd:CBITrfBonLogMsg.00.01.01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:CBI:xsd:CBITrfBonLogMsg.00.01.01
D:\java\projects\flowmanager-svn\converter\converter\docs\CBIInfTrfReq\xsd\CBITrfBonLogMsg.00.01.01.xsd">
	<LogMsgHdr>
		<MsgId>String</MsgId>
		<CreDtTm>2001-12-17T09:30:47.0Z</CreDtTm>
		<MsgTpCd>TRF-BON</MsgTpCd>
		<Sndr>
			<CUC>AAAAAAAA</CUC>
			<ABICd>00000</ABICd>
		</Sndr>
		<Rcvr>
			<CUC>AAAAAAAA</CUC>
			<SIACd>AAAAA</SIACd>
		</Rcvr>
		<NbOfDisp>2</NbOfDisp>
	</LogMsgHdr>
	<LogMsgCoreInf>
		<Disp>
			<NumDisp>2</NumDisp>
			<DispCreDt>000000</DispCreDt>
			<IBANBnNew>aa00a</IBANBnNew>
			<IBANBnOld>aa00a</IBANBnOld>
			<CRO>String</CRO>
			<Ord>String</Ord>
			<Benef>String</Benef>
			<CodRif>String</CodRif>
			<Descr>String</Descr>
			<CBIAddtlInf>String</CBIAddtlInf>
			<CBIAddtlInf>String</CBIAddtlInf>
			<CBIAddtlInf>String</CBIAddtlInf>
		</Disp>
	</LogMsgCoreInf>
</CBITrfBonLogMsg>
